apiVersion: v1
kind: Pod
metadata:
  name: busybox2
  labels:
    app: busybox2
  annotations:
    cni: flannel
spec:
  containers:
  - image: busybox:1.25.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox2
  restartPolicy: Always
