apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
  annotations:
    k8s.v1.cni.cncf.io/networks: flannel2-conf
spec:
  containers:
  - image: busybox:1.25.0
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox1
  restartPolicy: Always
