apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flannel1-conf
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "flannel",
    "name": "flannel.1",
    "subnetFile": "/run/flannel/subnet.env",
    "dataDir": "/var/lib/cni/flannel",
    "delegate": {
      "bridge": "cni0",
      "hairpinMode": true,
      "isDefaultGateway": true
    }
  }'
