apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: flannel2-conf
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "flannel",
      "name": "flannel.2",
      "subnetFile": "/run/flannel/network/subnet2.env",
      "dataDir": "/var/lib/cni/flannel/network2",
      "delegate": {
        "bridge": "cni1",
        "hairpinMode": true
      }
  }'
